== Case Class

Although very simple, let's discuss what case classes give us.

Lets start with a simple java-like class

```scala
class SimpleCircle(val radius: Double)
```

which generates something linke this using :

```
scala> :javap SimpleCircle
public class SimpleCircle extends java.lang.Object{
    public double radius();
    public void radius_$eq(double);
    public JavaCircle(double);
}
```

but if we want it to behave like http://en.wikipedia.org/wiki/Value_object[Value Object] 
we must override `equal` and `hashCode` methods (generate it by IDE). Now, scala for the rescue.

We can write
```scala
case class Circle(radius: Double)
```

and we gets class linke this in runtime

```
scala> :javap Circle
public class CaseCircle extends java.lang.Object implements scala.Product,scala.Serializable{
    public static scala.Function1 andThen(scala.Function1);
    public static scala.Function1 compose(scala.Function1);
    public double radius();
    public CaseCircle copy(double);
    public double copy$default$1();
    public java.lang.String productPrefix();
    public int productArity();
    public java.lang.Object productElement(int);
    public scala.collection.Iterator productIterator();
    public boolean canEqual(java.lang.Object);
    public int hashCode();
    public java.lang.String toString();
    public boolean equals(java.lang.Object);
    public CaseCircle(double);
}

```

as we can see, we have `equals` and `hashCode` generated by compile and mark class as Serializable.


More over case class is equipted with extractor (also generate by compiler in companion object). 
It can be used in pattern matching to simplified it.

``` scala
Crile(2.5) match {
  case Circle(r) => println("Radius = " + r)
}
```


Also compile is so kind to generate copy method, it is importent becouse case classes are *immutable*.
We can modify it only by creation new object with updating changed value. Example should take away doubt.

```scala
case class Point(x: Int, y: Int)

val a = Point(0,0)
val b = a.copy(y=10)
val c = b.copy(x=10)
```
so point `b` have cordinates `(0,10)`, and point `c` have `(10,10)`


More about case class can be found in http://www.scala-lang.org/files/archive/nightly/pdfs/ScalaReference.pdf#subsection.5.3.2[Scala Language Specification]

