== Case Class

WARNING: Is pulled in from PR and needs some fixes. TODO TODO

Although very simple, let's discuss what case classes give us. Example starts with simple java-like class

```scala
class SimpleCircle(val radius: Double)
```

which generates something like this on JVM :

```
scala> :javap SimpleCircle
public class SimpleCircle extends java.lang.Object{
    public double radius();
    public void radius_$eq(double);
    public JavaCircle(double);
}
```

but if we want it to behave like http://en.wikipedia.org/wiki/Value_object[Value Object] 
we must override `equal` and `hashCode` methods (generate it by IDE). Now, scala for the rescue.

We can add prefix `case` to class like this (class name was changed to avoid clashes)
```scala
case class Circle(radius: Double)
```

and we gets class like this in runtime (not full :javap is here to achive more clear point of view)

```
scala> :javap Circle
public class CaseCircle extends java.lang.Object implements scala.Serializable{
    public double radius();
    public CaseCircle copy(double);
    public double copy$default$1();
    public int hashCode();
    public java.lang.String toString();
    public boolean equals(java.lang.Object);
    public CaseCircle(double);
}

```

as we can see, we have `equals`, `hashCode` and `toString` generated by compile and mark class as Serializable.

Also compile is so kind to generate copy method, it is importent becouse case classes are *immutable*.
We can modify it only by creation new object with updating changed value. Example should take away doubt.

```scala
case class Point(x: Int, y: Int)

val a = Point(0, 0)
val b = a.copy(y = 10)
val c = b.copy(x = 10)
```
so point `b` have cordinates `(0, 10)`, and point `c` have `(10, 10)`

More over, case class is equipted with extractor (also generate by compiler in companion object). 
It can be used in pattern matching to simplified it.

``` scala
Crile(2.5) match {
  case Circle(r) => println("Radius = " + r)
}
```

More about case class can be found in http://www.scala-lang.org/files/archive/nightly/pdfs/ScalaReference.pdf#subsection.5.3.2[Scala Language Specification]

