== Enumeration

Scala does not have a build in "enum" like Java does. 
Instead we use a few tricks (embedded in Enumeration) to write something pretty similar.

=== Enumeration
The current (2.10.x) way of implementing an enum-like structure is by using the `Enumeration` class that comes with Scala:

```scala
object Main extends App {

  object WeekDay extends Enumeration {               <1>
    type WeekDay = Value                             <2>
    val Mon, Tue, Wed, Thu, Fri, Sat, Sun = Value    <3>
  }
  import WeekDay._                                   <4>

  def isWorkingDay(d: WeekDay) = ! (d == Sat || d == Sun)

  WeekDay.values filter isWorkingDay foreach println <5>
}
```
<1> First we declare an object that will hold our enumeration values, it has to extend Enumeration.
<2> Here we define an <<type-alias,Type Alias>> for Enumerations internal `Value` type, since we make the name match
    the object's name, we'll be able to refer to it consistently via "WeekDay" (yes, this is pretty much a hack)
<3> Here we use "multi assignment", so every val on the left-hand side gets assigned a different instance of Value. You could have written this as 7 val's.
<4> This import causes two things, first we can refer to `Mon` without prefixing it with `WeekDay`, but it also brings the `type WeekDay` into scope, so we can use it in the method definition bellow
<5> Lastly, we get some Enumeration methods. These are not really magic, most action happened when we create new Value instances

As you can see, it's actually not a built-in and is implemented by smartly using the Scala type system to make it look like an enum.
For some uses this may be enough but it's not as rich as the Java enum, where adding values and behavior to each case is possible.

=== @enum

WARNING: The `@enum` annotation is currently only a proposal, and is being discussed on scala-internals in the thread: https://groups.google.com/forum/#!topic/scala-internals/8RWkccSRBxQ%5B101-125-false%5D[enumeration must die].

Together with annotation macros which are coming in the future, we may be getting the `@enum` annotation, which is descibed somewhat in the related Scala Improvement Process document: <<enum-sip>>.

```scala
@enum
class Day {
  Monday    { def goodDay = false }
  Tuesday   { def goodDay = false }
  Wednesday { def goodDay = false }
  Thursday  { def goodDay = false }
  Friday    { def goodDay = true  }
  def goodDay: Boolean
}
```

