Links and Kudos
---------------

Obvisouly this vademecum required quite a bit of reseach and double-checking, so here are all the links I've found helpful (and you might too).

* Twitter's Scala School: http://twitter.github.io/scala_school quite a bit of Scala concepts. Which helped me a lot in nicely explaining Variance (nicest explanation I found, since "ever").
* Very old, but still valid explanation of Universal Types: http://www.scala-lang.org/old/node/128
* Existential Types by D.R. MacIver: http://www.drmaciver.com/2008/03/existential-types-in-scala/
* Scala Doc: http://www.scala-lang.org/api/current/index.html
* Wikipedia on the Diamond Problem: http://en.wikipedia.org/wiki/Diamond_problem#The_diamond_problem
* Safari Books online about Type Linearization: http://blog.safaribooksonline.com/2013/05/30/traits-how-scala-tames-multiple-inheritance/
* One of the first blogs about Phantom Types in Scala: http://blog.rafaelferreira.net/2008/07/type-safe-builder-pattern-in-scala.html
* Rogue (where I occasionally PullRequest too) is a great example of using Phantom Types: http://engineering.foursquare.com/2011/01/31/going-rogue-part-2-phantom-types/
* Great StackOverflow answer by **Kriss Nuttycombe** about Type Lambdas: http://stackoverflow.com/questions/8736164/what-are-type-lambdas-in-scala-and-what-are-their-benefits
* The :kind pull request to `scala`, by Adriaan Moors https://github.com/scala/scala/pull/2340
I would especialy like to thank all proof-readers and reviewers tha that have helped me with polishing this article and giving valuable feedback many many times (in chronological order :-)):

* Sergio Rodrigez, for the most in depth article review I've ever seen in my life and lots of suggestions,
* Andrzej Grzesik, fellow PolishJUG / GeeCON guy
* Joshua Sureth, for the awesome comments and examples over lunch after devoxx
* The awesome guys from Softwaremill
* The awesome guys from VirtusLab
* TODO TODO

Give back some kudos! Share this page if you liked it using IRC, or social networks :-)

++++
<!-- Place this tag where you want the +1 button to render. -->
<div class="g-plusone"></div>

<!-- Place this tag after the last +1 button tag. -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
++++

++++
<a href="https://twitter.com/share" class="twitter-share-button" data-via="twitterapi" data-lang="en">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
++++

++++
<script type="text/javascript" src="http://www.reddit.com/static/button/button1.js"></script>
++++
