=== Thanks and kudos

I would especialy like to thank all proof-readers and reviewers tha that have helped me with polishing this article and giving valuable feedback many many times (in chronological order :-)):

* Sergio Rodrigez, for the most in depth article review I've ever seen in my life and lots of suggestions,
* Andrzej Grzesik, fellow http://java.pl[PolishJUG] / http://geecon.org[GeeCON] guy
* Josh Sureth, for the awesome comments and examples over lunch after devoxx
* The awesome people from http://softwaremill.com[SoftwareMill] for reviews and comments
* The awesome people from http://virtuslab.com[VirtusLab] for typo fixes, the makefile and suggestions
* The http://www.krakowscala.pl[Kraków Scala User Group]'s members, for proof reading and suggestions
* All the kind people who pull-requested typo's and small fixes
* _TODO, there's more people_
* You! Really. Thanks for reading this, you rock.

Pull requests and comments are very welcome, if you're up to it please go ahead, here's the https://github.com/ktoso/scala-types-of-types[git repository].

That's all folks, and if it's not, please ping me and I'll update the guide. _Life is Study!_ -- mailto:konrad.malawski@java.pl[Konrad 'ktoso' Malawski]

=== Give back some kudos!
If you liked this page, please share it with your friends using IRC any other chat service, or email, or social networks using these clicky-clicky buttons bellow! :-)

++++
<!-- Place this tag where you want the +1 button to render. -->
<div class="g-plusone"></div>

<!-- Place this tag after the last +1 button tag. -->
<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
++++

++++
<a href="https://twitter.com/share" class="twitter-share-button" data-via="twitterapi" data-lang="en">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
++++

++++
<script type="text/javascript" src="http://www.reddit.com/static/button/button1.js"></script>
++++
