== Self-Recursive Type

Self-recursive Types are referred to as **F-Bounded Types** in most literature, so you may find many articles or blog posts referring to "F-bounded".
Actually, this is just another name for "self-recursive" and stands for situations where _the subtype constraint itself is parametrized by one of the binders
 occurring on the left-hand side_. Since the wording self-recursive is more intuitive, let's stick to it for the rest of the section (while the subsection
 title is aimed to assist people who try to google what "F-bounded" means).

=== F-Bounded Type

While this not being a Scala specific type, it still sometimes raises a few eyebrows. One example of a self-recursive type many of us are (perhaps unknowingly) familiar with, is Java's `Enum<E>`, if you're curious about it, check out the http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/lang/Enum.java[Enum sources from Java]. But now back to Scala and first let's see what we're actually talking about.

TIP: For this section we will not dive very deep into this type. If you're curious for a more in-depth use-case in Scala, you may look into Kris Nuttycombe's http://logji.blogspot.se/2012/11/f-bounded-type-polymorphism-give-up-now.html[F-Bounded Type Polymorphism Considered Tricky].

Imagine you have some `Fruit` trait, and both an `Apple` and an `Orange` extend it. The Fruit trait also has a "compareTo" method, and here the problem comes up: imagine you'd want to say "_I can't compare oranges with apples, they're totally different things!_". First let's look at how we lose this compile-time safety with the naive implementation:

```scala
// naive impl, Fruit is NOT self-recursively parameterised

trait Fruit {
  final def compareTo(other: Fruit): Boolean = true // impl doesn't matter in our example, we care about compile-time
}

class Apple  extends Fruit
class Orange extends Fruit

val apple = new Apple()
val orange = new Orange()

apple compareTo orange // compiles, but we want to make this NOT compile!
```

In the naive implementation, since the trait `Fruit` has no clue about the types extending it, it's not possible to restrict the compareTo signature to
 allow only "_the same subclass as_ ``this``" in the parameter. Let's now rewrite this example to use a *Self Recursive Type Parameter*:

```scala
trait Fruit[T <: Fruit[T]] {
  final def compareTo(other: Fruit[T]): Boolean = true // impl doesn't matter in our example
}

class Apple  extends Fruit[Apple]
class Orange extends Fruit[Orange]

val apple = new Apple
val orange = new Orange
```

Notice the Type Parameter in Fruit's signature. You could read it as "I take some `T`, that `T` must be a `Fruit[T]` ", and the only way to satisfy such
bounds is by extending this trait as we do with `Apple` and `Orange` now. Now if we'd try comparing `apple` to `orange` we'll get a compile time error:

```repl
scala> orange compareTo apple
<console>:13: error: type mismatch;
 found   : Apple
 required: Fruit[Orange]
              orange compareTo apple

scala> orange compareTo orange
res1: Boolean = true
```

So now we're sure we'll only ever compare apples with apples, and other Fruit with the same kind (_sub-class_) of `Fruit`. There's more to discuss here
though - what about subclasses of `Apple` and `Orange`? Well, because we "filled in" the type parameter at Apple / Orange level in the type hierarchy, we basically said "apples can only be compared to apples", which means that sub-classes of apples, can be compared with each other - Fruit's signature of `compareTo` will still be happy, because the right hand side of our call would be some `Fruit[Apple]` -- only a bit more concrete, for example let's try this with a japanese apple (ja. "りんご", "ringo") and a polish apple (pl. "Jabłuszko"):

```scala
object `りんご`  extends Apple
object Jabłuszko extends Apple

`りんご` compareTo Jabłuszko
// true
```

TIP: You could get the same type safety using more fancy tricks, like path dependent types or implicit parameters and type classes. But the simplest thing
that does the job here would be this.


