== Type Annotation

Scala has Type Inference, which means that we can skip telling the Type of something each time in the source code,
and instead we just use `val`s or `def`s without "saying the type explicitly in the source". This being explicit about
the type of something, is called an Type Annotation.

```scala
trait Thing
def getThing = new Thing

// without Type Annotation, the type is infered to be `Thing`
val infered = getThing

// with Type Annotation
val thing: Thing = getThing
```

In these situations, leaving out the Type Annotation is OK. Although you may decide to always annotate return types of public methods (*that's very good idea!*) in order to make the code more self-documenting.

In case of doubt you can refer to the below hint-questions to wether or not, include a Type Annotation.

* Is it a parameter? **Yes**, you have to.
* Is it a public methods return value? **Yes**, for self-documenting code and control over exported types.
* Is it a recursive or overloaded methods return value? **Yes**, you have to.
* Do you need to return a more general interface than the inferencer would find? **Yes**, otherwise you'd expose your implementation details for example.
* Else... No, don't include a Type Annotation.
* Related hint: Including Type Annotations speeds up compilation, also it's generally nice to see the return type of a method.

So we put Type Annotations after value names. Having this said, let's jump into the next topics, where these types will become
more and more interesting.

