== Type Class +++<span style="color:red">&#x2717;</span>+++

Type Classes belong to the most powerful patterns available to use in Scala, and can be summed up (if you like fancy wording) as "ad-hoc polymorphism" which should be understandable once we get to the end of this section.

The typical problem Type Classes solve for us is providing extensible APIs without explicitly binding two classes together.
An example of such a strict binding, we would be able to avoid using Type Classes, is for example extending a `Writable` interface,
in order to make our custom data type writable:

```scala
// no type classes yet
trait Writable[Out] {
  def write: Out
}

case class Num(a: Int, b: Int) extends Writable[Json] {
  def write = Json.toJson(this)
}
```

Using this style, of just extending and implementing an interface, we have bound our `Num` to `Writable` and also, we had to provide the implementation for `write`, "right there, right now", which makes it harder for others to provide a different `write` implementation - they would have to subclass `Num`! Another pain point here is that we cannot extend two times from the same trait, providing different serialization targets (you can't both extend `Writable[Json]` and `Writable[Protobuf]`).

All these problems can be addressed by using a Type Class based approach instead of directly extending `Writable[Out]`. Let's give it a shot, and explain in detail how this is actually working:

```scala
trait Writes[In, Out] {                                               <1>
  def write(in: In): Out 
}

trait Writable[Self] {                                               <2>
  this: Self =>

  def write[Out]()(implicit writes: Writes[Self, Out]): Out = 
    writes write this
}

implicit val jsonNum = Writes[Num, Json] {                            <3>
  def write(n: Num) = Json.toJson(n)
}

case class Num(a: Int) extends Writable[Num]
```
<1> First we define out Type Class, its API is similar to the previous `Writable` trait we, but instead of mixing it into a class that will be written, we
will keep it separate, and in order to know what it's defined _for_ we use the `Self` <<Type Parameter, type-parameter>>
<2> Next we change our `Writable` trait to be parameterized with `Self` and the target serialization type is moved onto the signature of `write`. It also now
 requires an implicit `Writes[Self, Out]` implementation, which handles the serializing - that's an instance of our Type Class.
<3> This is the actual implementation of the Type Class, notice that we mark the instance as `implicit`, so it's available for the `write()(implicit Writes[_, _])` method
